version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build: .
    image: ghcr.io/thalkz/kart_server
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "80:80"

volumes:
  data:
