version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    image: thalkz/kart_server
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "3000:3000"

  app:
    build:
      context: ./app
      args:
        - SERVER_HOST=http://server
        - SERVER_PORT=3000
    image: thalkz/kart_app
    ports:
      - "80:80"

volumes:
  data:
