version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    image: thalkz/kart-server:latest
    build:
      context: ./server
    env_file:
      - .env
    depends_on:
      - database
    platform: "${PLATFORM_ARCH}"
    ports:
      - "443:443"

  web:
    image: thalkz/kart-web:latest
    build:
      context: ./app
    env_file:
      .env
    platform: "${PLATFORM_ARCH}"
    ports:
      - "8080:80"
  
  reverse-proxy:
    image: thalkz/kart-reverse-proxy:latest
    build:
      context: ./reverse_proxy
    depends_on:
      - server
    platform: "${PLATFORM_ARCH}"
    ports:
      - "80:80"

volumes:
  data:
