version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    image: thalkz/kart_server
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  app:
    build:
      context: ./app
    image: thalkz/kart_app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  data:
