version: "3.7"

services:
  database:
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build: .
    image: ghcr.io/thalkz/kart_server
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    volumes:
      - ./migrations:/server/migrations/

volumes:
  data: