version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env-local
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build: .
    image: ghcr.io/thalkz/kart_server
    restart: always
    env_file:
      - .env-local
    depends_on:
      - database
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
      - "80:80" # For redirection to https
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

volumes:
  data: