version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    env_file:
      - .env
    depends_on:
      - database
    platform: "${PLATFORM_ARCH}"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
volumes:
  data:
