name: Release to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Build and push app image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: thalkz/kart_app:latest,thalkz/kart_app:${{ steps.tagName.outputs.tag }}
          build-args:  |
            SERVER_HOST=http://server
            SERVER_PORT=3000

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: thalkz/kart_server:latest,thalkz/kart_server:${{ steps.tagName.outputs.tag }}
