name: Release to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag kart_server --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Push image
        run: |
          docker tag kart_server ghcr.io/thalkz/kart_server:${{ steps.tagName.outputs.tag }}
          docker tag kart_server ghcr.io/thalkz/kart_server:latest
          docker push ghcr.io/thalkz/kart_server
